services:
  backend:
    restart: always
    build: backend/
    ports:
      - "3000:3000"
  web:
    build: web/
    ports:
      - "80:80"

  database:
    build: 
      context: database/

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: