services:
  backend:
    build: backend/
    ports:
      - "9000:9000"
  web:
    build: web/
    ports:
      - "80:80"

  database:
    build: 
      context: database/

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"